# Generated by Django 4.2.8 on 2024-02-05 06:28

from django.db import migrations, models
import employee_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('experiance', models.IntegerField()),
                ('emp_id', models.CharField(max_length=100)),
                ('id_card', models.FileField(upload_to=employee_app.models.EmployeeDetailsModel.namefile)),
            ],
        ),
    ]
