# Generated by Django 4.2.8 on 2024-02-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_employeedetailsmodel_emp_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=100)),
                ('required_time', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employeedetailsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ExperianceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employeedetailsmodel')),
            ],
        ),
    ]
